@warning_ignore_restore("unreachable_code")

func test():
	pass
